### ISSUE TITLE
npm i error   Node.js 20.3.0

### ISSUE THREAD

**Issue by zhuoshengjie** [ladit/astro-blog-zozo#3]
![image](https://github.com/ladit/astro-blog-zozo/assets/47313110/1054ad6b-fe08-4788-9164-9224bda29321)

**Comment by ladit** [comment]
fixed in this [commit](https://github.com/ladit/astro-blog-zozo/commit/79d43b3aff3db245c6c9ada9c25c248d2f25f957)
